### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by soleti** [jacg/nain4#1]
Hello, 

I've just tried installing Nix on macOS, but I get this error: 
```
% nix develop --extra-experimental-features 'nix-command flakes'
error: flake 'git+file:///Users/roberto/nain4' does not provide attribute 'devShells.aarch64-darwin.default', 'devShell.aarch64-darwin', 'packages.aarch64-darwin.default' or 'defaultPackage.aarch64-darwin'
       Did you mean devShell?
```
Is there something I can do or there is no Apple Silicon support?

**Comment by jacg** [comment]
Hi,

As I've written in the README which I'm hurriedly updating (now that you're all starting to use this!) I do not know the status of support on MacOS, yet. It is quite possible that Apple Silicon is not supported, or it might be a configuration problem introduced by me. As I do not have access to any physical MacOS machines myself, it's rather difficult for me to verify exactly what the situation is.

**BUT** your issue relates to the flake which provides the Geant4 development environment, and I think that you are interested in `nain4`, which doesn't need that environment at all, in order to be used. 

I am putting both of them in this repository, because automated testing is half the reason for the existence of `nain4` and without a Geant4 installation, there is no way to test `nain4`.

You *should* be able to use `nain4` with any installation of Geant4 that you have, and not bother with the flake at all, but I have not yet provided an easy way of doing it. This is one of my top priorities. Any help from someone who knows more about `cmake` than I do (which is very little) would be very welcome.

`nain4` has, so far lived entirely inside the project for which it was created, and the first thing I have to do is to decouple it from its parent project. *Work In Progress.*

**Comment by soleti** [comment]
Ok, I understand. Could we maybe consider using Docker instead of Nix in order to provide a clean separation between nain4 proper and its environment? If the goal is shipping a reproducible environment and automated tests, this might be easier to achieve with Docker+GitHub Actions. Docker has the advantage of being well supported on all common platforms and well documented. IMHO it's also more user friendly (of course it doesn't serve the same purpose as nix but if those above are our needs I think it's a good fit). 

Just food for thought since the project is still in its initial phase.

**Comment by jacg** [comment]
Nix can [generate docker images](https://nixos.org/#asciinema-demo-example_4), so adding docker support should be easy. But reproducibility (and composability, and ...) is far superior in Nix, so I'll keep that as the underlying specification.

**Comment by jacg** [comment]
I don't understand. Does it make any difference to any end-user of a docker image, whether the image was created by hand or automatically generated from Nix or any other specification?

With Nix, you get Docker for free (and Singularity, and probably more); with Docker you get just Docker.

If Docker solves problems for a Apple Silicon user, why would it matter how the image content is specified? Maybe I'm missing something.

**Comment by soleti** [comment]
I am not a nix expert, but I don't understand how nix can generate a Docker image that runs on Apple Silicon if it's not possible to install it on Apple Silicon. Maybe I am confused?

**Comment by jacg** [comment]
I had a brief look at how things work in Docker on Apple Silicon, but quickly gave up, as this is not a good use of my time.

It is unfortunate that `nain4` is sharing a repository with the flake, as the flake is drawing attention away from `nain4`. The cohabitation is a short-term convenience, to allow `nain4`'s (currently) only developer to get on with writing and running automated tests. I will have to de-emphasize, hide or even remove the flake. In the meantime, I suggest you forget that it's here.

Earlier you wrote

> Could we maybe consider using Docker instead of Nix in order to provide a clean separation between nain4 proper and its environment?

Separation of `nain4` from its environment will be done with cmake. Nix, Docker, or manual Geant4 installation *are* the environment. As soon as `nain4` is a discoverable cmake package, the flake can move out of the `nain4` repo into its own home. It probably won't happen immediately, though, as there is so much more urgent work to be done on `nain4` and the flake doesn't get in anyone's way (or it won't, if it is not mentioned in the README).

**Comment by soleti** [comment]
Thank you for looking into this. Just to be sure: at the moment there is no "official" way to build nain4 on a system without nix using an existing Geant4 installation right? Or am I missing something?

**Comment by jacg** [comment]
It's easy to build it with cmake. I trust that this is acceptable to pretty much everyone, given that cmake is the official mechanism for compiling Geant4 applications.

I am currently traveling, but @gonzaponte is working on a streamlined cmake recipe for including `nain4` as an external project, which will become official once we have tested it thoroughly.

In the meantime, @Hiitsaso and @mdcge are using the simple hack of copying the nain4 source tree into their projects and adding `add_subdirectory(Nain4)` to their `CMakeList.txt`s. This works just fine with @Hiitsaso's non-Nix Geant4 installation.

**Comment by jacg** [comment]
It's easy to build it with cmake. I trust that this is acceptable to pretty much everyone, given that cmake is the official mechanism for compiling Geant4 applications.

I am currently traveling, but @gonzaponte is working on a streamlined cmake recipe for including `nain4` as an external project, which will become official once we have tested it thoroughly.

In the meantime, @Hiitsaso and @mdcge are using the simple hack of copying the nain4 source tree into their projects and adding `add_subdirectory(Nain4)` to their `CMakeList.txt`s. This works just fine with @Hiitsaso's non-Nix Geant4 installation.

It's a horrible hack, but it lets them get on with it while we work on a decent solution.

**Comment by jacg** [comment]
@soleti, could you please verify that [these instructions](https://jacg.github.io/nain4/how-to/enable-nain4-in-cmake.html) work for you?

**Comment by soleti** [comment]
I get this error now after doing `just`:

```CMake Error at build/_deps/nain4-src/nain4/CMakeLists.txt:58 (find_package):
  By not providing "FindCatch2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Catch2", but
  CMake did not find one.

  Could not find a package configuration file provided by "Catch2" with any
  of the following names:

    Catch2Config.cmake
    catch2-config.cmake

  Add the installation prefix of "Catch2" to CMAKE_PREFIX_PATH or set
  "Catch2_DIR" to a directory containing one of the above files.  If "Catch2"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
error: Recipe `run` failed with exit code 1```

**Comment by gonzaponte** [comment]
BTW, we can also provide Catch2 via FetchContent, if that makes things easier.

**Comment by soleti** [comment]
Naively, I added 
```
FetchContent_Declare(
  Catch2
  GIT_REPOSITORY https://github.com/catchorg/Catch2.git
  GIT_TAG        v3.3.2
  SOURCE_SUBDIR  src
)
FetchContent_MakeAvailable(Catch2)
```

But I get

```(base) roberto@Stefanos-MacBook-Pro double-sipm % just 
CMake Error at build/_deps/catch2-src/src/CMakeLists.txt:1 (include):
  include could not find requested file:

    CatchMiscFunctions


CMake Error at build/_deps/catch2-src/src/CMakeLists.txt:327 (source_group):
  source_group unknown error.


CMake Error at build/_deps/catch2-src/src/CMakeLists.txt:338 (add_build_reproducibility_settings):
  Unknown CMake command "add_build_reproducibility_settings".


-- Configuring incomplete, errors occurred!```

**Comment by jacg** [comment]
Hmm, [Catch2](https://github.com/catchorg/Catch2) is a dev dependency, for running the tests. `just` runs all the tests., so it needs Catch2.

Because the flake takes care of providing all the dependencies, it's easy to forget that people who don't use the flake, have to get Catch2 (and any other dependencies) by their own means.

A fairly obvious thing to do, would be to provide Catch2 using similar cmake mechanisms (as has already been suggested), but I do want the flake to be the official source of truth as to the exact version numbers.

**Comment by soleti** [comment]
I think it's important to provide an easy and cross-platform way to install nain4 that doesn't rely necessarily on a Nix flake (which after all is also an experimental feature). Unfortunately simply adding Catch2 via FetchContent doesn't seem to work.

**Comment by gonzaponte** [comment]
Please try with v2.x, which is the one being used by nix (I think)

**Comment by jacg** [comment]
The flake uses Catch2 2.13.10.

https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=catch2

**Comment by soleti** [comment]
If I try with v2.13.10 (which is the latest v2.x version as far as I can see) we go back to:
```
CMake Error at build/_deps/nain4-src/nain4/CMakeLists.txt:58 (find_package):
  By not providing "FindCatch2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Catch2", but
  CMake did not find one.

  Could not find a package configuration file provided by "Catch2" with any
  of the following names:

    Catch2Config.cmake
    catch2-config.cmake

  Add the installation prefix of "Catch2" to CMAKE_PREFIX_PATH or set
  "Catch2_DIR" to a directory containing one of the above files.  If "Catch2"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by gonzaponte** [comment]
Is this without SOURCE_SUBDIR?

**Comment by soleti** [comment]
> Is this without SOURCE_SUBDIR?

Yes, `SOURCE_SUBDIR  src`

**Comment by gonzaponte** [comment]
I believe that line doesn't belong there, can you delete it and try again?

**Comment by soleti** [comment]
> I believe that line doesn't belong there, can you delete it and try again?

Same error unfortunately. To be clear, I have:
```
FetchContent_Declare(
  Catch2
  GIT_REPOSITORY https://github.com/catchorg/Catch2.git
  GIT_TAG        v2.13.10
)
FetchContent_MakeAvailable(Catch2)
```

**Comment by gonzaponte** [comment]
I am not able to reproduce. With this:
```
include(FetchContent)
FetchContent_Declare(
  Catch2
  GIT_REPOSITORY https://github.com/catchorg/Catch2.git
  GIT_TAG        v2.13.10
# This line is just for me so it doesn't attempt to find a different installation of Catch2
  OVERRIDE_FIND_PACKAGE 
)
FetchContent_MakeAvailable(Catch2)
find_package(Catch2 REQUIRED)
```

my cmake fails when it reaches this line later on:
```
include(Catch)
```

But your error happens when calling `find_package`. Not sure how to help.

**Comment by jacg** [comment]
Passing the baton to #15
