### ISSUE TITLE
Usage of GenericMessenger in nain4

### ISSUE THREAD

**Issue by Aretno** [jacg/nain4#100]
So far I've been unable to implement a working GenericMessenger, I saw that there are plans to include a custom messenger in nain4 (#14) but I've been trying to use the G4 one with no luck. To keep the function argument of `.geometry` I created a lambda function that returns the geometry function with an argument.

I'm guessing it has something to do with when things are initialized and then read from the macro, but not really sure what is the issue here. 

Note that I'm trying to avoid creating custom classes as was usually done in G4 for each step, I understood from conversations with the summer students that that was desirable. I'm unsure if that is being an issue here as in G4 one had the messenger as a variable of the detector construction class.

In any case, the code is here: https://github.com/Aretno/lxe_sphere/tree/add_messenger

**Comment by gonzaponte** [comment]
> I'm guessing it has something to do with when things are initialized and then read from the macro, but not really sure what is the issue here.

I believe you are correct. I'm not 100% familiar with how G4 handles the messengers, but I think the argument goes along those lines.

> Note that I'm trying to avoid creating custom classes as was usually done in G4 for each step

This is not a requirement, but creating a function is usually simpler as it involves less boilerplate (this is a big chunk of what n4 does for you). For the time being, if having messengers is a must for you, I'm afraid you will have to stick to classes. On the other hand, your project seems small enough for compilation times to be short, so if you don't plan to switch values very frequently you might get away with leaving them hard-coded.


We will almost certainly implement something for the messenger, but I can't say how soon this feature will be delivered.

**Comment by jacg** [comment]
I had some messengers with proto-nain4 [here](https://github.com/jacg/explore-G4/tree/master/abracadabra/src/messengers), and I vaguely recollect that there are issues with the order in which things are done by G4, but those will be dealt with in the main file, which I wouldn't want to unleash on even my worst enemies. I'll have to find the time to reacquaint myself with the details.

> Note that I'm trying to avoid creating custom classes as was usually done in G4 for each step

The aim is for `nain4` not to stand in your way if you want to do anything using classical G4 techniques. The aim is to provide a better way to do things, wherever possible and subject to having the resources available to design and implement them.

So, the absence of something in n4 shouldn't stop you from progressing if you know how to do it in G4. But we certainly welcome suggestions of things that could be usefully added to n4.

The other point is that, for *simple* things, classes are often overkill, and a bunch of lambas sharing enclosed variables is often much clearer and more concise than writing classes. (This is especially important for writing automated tests: if you had to write classes for everything, writing tests would be prohibitively expensive.) But as the code gets more complex, so the balance shifts towards classes being more appropriate than lambdas.  In summary, you shouldn't try to avoid classes at all costs, only in those cases where a a few lambdas injected into n4 abstractions are more convenient that full-blown hand-written classes.

**Comment by jacg** [comment]
We definitely have to add a reliable and convenient means of setting arbitrary parameters via G4 macros.

So the recompilation will only be a temporary solution. Hopefully we'll have something ready without too much delay.

**Comment by gonzaponte** [comment]
> I would not know how to pass that to nain4 run_manager as if I'm understanding correctly, geometry wouldn't take that as an argument. 

The following options should work for you:

```
n4::run_manager::create()
.physics(...)
```
1. `.geometry(new your_class(with, some, arguments))`
2. `.geometry<your_class>(arguments, to, your, class)`

We think option 2 is preferred over option 1, but both of them are available.

**Comment by Aretno** [comment]
I tried option 2 and while it runs, it still does not cares about the messenger at all, to my surprise... Anyway, since this is kind of urgent for me I'll go ahead with the recompilation. Thanks for the input!
