### ISSUE TITLE
How to set up a sensitive detector.

### ISSUE THREAD

**Issue by Aretno** [jacg/nain4#101]
Hi there,

just a quick question, is there any short example available where a sensitive detector actually being used within nain4? Before scratching my head too much I figured I could ask. If not available, here are some concrete questions:

1) Can I declare a volume as sensitive at the same command of declaration? I saw the `sensitive_detector` class but I'm unsure if that can be chain with the geometry construction. If not I'm guessing I shall retrieve the logical volume and set the sensitive detector (declared with nain4) in the G4 standard way.

2) Am I right to understand there are 3 different functions that can be passed to the `sensitive_detector` class, a `process_hits`, a `init` and an `end_of_event`? If so, how exactly is this done? Declaring the `sensitive_detector` and then setting somehow the functions? Or is there a way to pass them in the constructor?

Thanks a lot for the help.

**Comment by gonzaponte** [comment]
> Can I declare a volume as sensitive at the same command of declaration? 

Yes!
First instantiate the sd:

```
auto sd = (new n4::sensitive_detector(a_unique_name_for_each_sd, process_hits_fn)
  -> initalize   (initializing_fn) // optional
  -> end_of_event(end_of_event_fn) // optional
);
```
And then you can assign it to any volume like
```
n4::some_solid(name).dimensions(...).sensitive(sd).volume(material);
```
or
```
n4::some_solid(name).dimensions(...).sensitive(sd).place(material).other.stuff().now();
```


[ Here](https://github.com/jacg/nain4/blob/e8cc68b514927890fd01e2aa38f8dd5995df83cb/examples/00-basic/n4app.cc#L44) is an example used in context.



>  I shall retrieve the logical volume and set the sensitive detector (declared with nain4) in the G4 standard way.

This is always an option. But in this case, we do have it already implemented in n4.

**Comment by jacg** [comment]
A bit of background rationalization: `G4VSensitiveDetector` has one purely-virtual function (process hits) so the client *must* define it, and that is why `n4::sensitive_detector` takes it as a construction argument. The other two methods have a (nullop) default implementation, that's why you may add them afterwards with the `initialize` and `end_of_event` methods of `n4::sensitive_detector`.

This is an example of how `nain4` tries to make it impossible to express nonsensical situations at compile time.

**Comment by Aretno** [comment]
Thanks to both of you, I have managed to use the sensitive detector and store the information. The rationalization was rather helpful, it really clarifies the intend and understand the approach/philosphy.
