### ISSUE TITLE
Variety of english

### ISSUE THREAD

**Issue by gonzaponte** [jacg/nain4#119]
Geant4 doesn't settle for BrE or AmE[^1], should we stick to one of them? If so, which one?

[^1]: For instance, both `rg -i initialise` and `rg -i initialize` yield plenty of matches in the source directory of G4.

**Comment by jacg** [comment]
Not many people know this, but -ize was the preferred *British* English spelling for many centuries and  the phenomenon of Brits preferring -ise is only a few decades old. Call me old-fashioned, but even though my English is unapologetically British, I will continue to (unapologetically) use -ize endings as well as to spell colour with an 'o' and insist that data are plural and datum is singular (hence, 'these data' and 'this datum').

I appreciate that it would be convenient, for the purposes of searching, if we had consistent spelling everywhere, but it's a pipe dream. As we have no automatic tests we can run for consistency of English spelling in our code and documentation, inconsistencies will definitely creep in.

So I don't think there is any point in wasting any time or effort on this.

**Comment by gonzaponte** [comment]
Ok
