### ISSUE TITLE
CLI support

### ISSUE THREAD

**Issue by gonzaponte** [jacg/nain4#122]
To be edited if more options are found.

Options:
+ Write our own CLI interface
  - Flexible, can be tailored to our needs
  - Requires (a lot of) development
+ [argparse](https://github.com/p-ranav/argparse)
  - Available (and up-to-date) in nixpkgs
  - Actively maintained
  - Reasonable syntax
+ [argumentum](https://github.com/mmahnic/argumentum)
  - Not in nixpkgs
  - Actively maintained
  - Doubts about the syntax

**Comment by jacg** [comment]
`argumentum` uses `std::optional` for optional arguments, while `argparse` does something more ugly.

`argumentum` seems to be cmake-based, so it is likely to be almost trivial to create a Nix derivation for it, which we could use as an overlay, and even submit for inclusion in `nixpkgs`.

But I'll persevere a bit more with `argparse`.

**Comment by jacg** [comment]
`argparse` seems to be adequate for our immediate needs.

**Comment by gonzaponte** [comment]
Done in 96ac1ea7359d384f49da06a5d587218be497d159
