### ISSUE TITLE
Default value for --vis-macro only works if passed last on CLI

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#134]
These work:
```sh
just run -n 10       -g
just run -n 10       -g vis2.mac
just run -g vis2.mac -n 10
```
but this one crashes:
```sh
just run -g          -n 10
```

**Comment by gonzaponte** [comment]
IIUC, the fact that  `just run -g -n 10` crashes, is expected. Essentially `-g`  without an argument means `-g "T"`, which replaces the default value and ends up executing a command like `/control/execute` without arguments, which causes the crash. This makes sense to me. However, I'm worried that `just run -n 10 -g` doesn't do the same.

**Comment by jacg** [comment]
> `-g` without an argument means `-g "T"`

Why? Where does the `"T"` come from?

The whole point of 16602fb89cc98c03101ac0ff89b91822792c84cd was to give `-g` the default value `vis..mac` , so `just run -n 10 -g` does exactly what it's supposed to do, and `just run -g -n 10` is broken.

**Comment by gonzaponte** [comment]
> Why? Where does the "T" come from?

I don't know where that `"T"` came from, I must have typed it accidentally after writing the post. I meant `""`.

But I was wrong, The program doesn't crash because it picks up an empty string, but rather because it doesn't pick up anything. It expects an argument and there isn't one. I interpret the default value in argparse to mean "if -g is not provided", not "if -g is not followed by an argument".

These two work the same way:
`just run -n 10 -g ""`
`just run -g "" -n 10`

Which is consistent. What's not consistent is that `just run -n 10 -g` works.

**Comment by jacg** [comment]
> I interpret the default value in argparse to mean "if -g is not provided", not "if -g is not followed by an argument".

I found it difficult to reconcile what is written in the docs about `default_value`, `implicit_value` and `is_used`, with observable reality, at least in the time I had available.

**Comment by jacg** [comment]
It looks like `implicit_value` is the correct thing to use in this case.

It will be fixed if and when #142 is merged.

**Comment by jacg** [comment]
Done in b372d0ecea5be91b4284e2d2eb2f0013cc8440cf.

**Comment by jacg** [comment]
The previous fix seems to have broken the ability to pass a vis macro explicitly.

There seems to be no happy interaction between `default_value` and `implicit_value` in `argparse`.

**Comment by jacg** [comment]
The `argparse` README points out that `argparse::nargs_pattern::optional` is equivalent to the `?` in Python's version of `argparse`
```c++
program.add_argument("--input_files")
  .nargs(argparse::nargs_pattern::optional);  // "?" in Python. This accepts an argument optionally.
```
The documentation on Python's version has this to say about `?`


> '?'. One argument will be consumed from the command line if possible, and
> produced as a single item. If no command-line argument is present, the value
> from default will be produced. Note that for optional arguments, there is an
> additional case - the option string is present but not followed by a
> command-line argument. In this case the value from const will be produced.
> Some examples to illustrate this:
> ``` python
> parser = argparse.ArgumentParser()
> parser.add_argument('--foo', nargs='?', const='c', default='d')
> parser.add_argument('bar', nargs='?', default='d')
> 
> parser.parse_args(['XX', '--foo', 'YY'])
> Namespace(bar='XX', foo='YY')
> 
> parser.parse_args(['XX', '--foo'])
> Namespace(bar='XX', foo='c')
> 
> parser.parse_args([])
> Namespace(bar='d', foo='d')
> ```

which implies that, in Python, what we need could be achieved with 

+ `nargs='?''`
+ `const='vis.mac'`
+ `default='some marker value indicating absence'`

but AFAICT the C++ version doesn't provide anything equivalent to Python's `const` on which this solution depends.

**Comment by jacg** [comment]
An automated test for this has now been merged.

**Comment by jacg** [comment]
The above test was commented out on `master`. It is uncommented on [vis-cli-arg](/jacg/nain4/tree/vis-cli-arg), which I have linked to this issue.
