### ISSUE TITLE
Consider replacing header guards with #pragma once

### ISSUE THREAD

**Issue by gonzaponte** [jacg/nain4#150]

**Comment by jacg** [comment]
Here is some background info:

+ https://github.com/IncludeGuardian/pragma-once-issues-tests
+ https://includeguardian.io/article/pragma-once-vs-ifndef

I've implemented the change and it [passes](https://github.com/jacg/nain4/actions/runs/6404473072) on GHA.

Is there any reason to delay this?

I would certainly want it in *before* we start reorganizing the headers, which is pretty much the next nontrivial task to be done.
