### ISSUE TITLE
Consider running GHA with gcc in addition to clang

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#17]
Does anyone use `gcc` on MacOS?

**Comment by jacg** [comment]
We got an error when we bumped the version of `nain4` in `GaP` and the user was using `gcc`. `clang` was perfectly happy.

IIRC, it was two `using CLHEP::pi`s in the same scope.

**Comment by gonzaponte** [comment]
Yes, fixed [here](https://github.com/jacg/nain4/commit/dc6fc98776ccbd26555a743cd7b3000129d34d86)

**Comment by jacg** [comment]
The point being that we have a concrete example of why we need to run `gcc` on GHA.
