### ISSUE TITLE
Better interfaces for constructing G4 Solids

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#25]
The constructors of the G4 Solids take a large number of mandatory arguments. Remembering their order and meaning is a cognitive burden, and being obliged to pass in those that frequently take on obvious default values (such as inner radii which are often zero, and `G4Tubs`' angles which are often 0° & 360°) is a waste of space and source of noise and confusion.

How can we do better?

An obvious idea is to use the builder pattern, like we already do in `n4::place`.

If every single parameter has to be set by a separate builder method, it could get very verbose. So we should provide methods that accept a bunch of arguments that are related, in one go. Similar to the `.at()` methods in `n4::place`.

It's a shocking oversight that `G4Box` doesn't have a constructor that takes its dimensions as a single G4ThreeVector.

I'm sure that, with a bit of thought, we can make vast improvements on the interface for construction of G4Solids.

Whatever we do here, would have to be integrated with `n4::volume`.

**Comment by jacg** [comment]
The half-sizes also frequently lead to immense verbosity.

**Comment by jacg** [comment]
This is moving along nicely. Once we've done boolean solids (#5, #22), this in done in principle. In practice we'll need to add `n4::solid` implementations for more `G4VSolid`s, but that's just a question of going through the motions; the design will be finalized when the booleans are added.

**Comment by jacg** [comment]
Geant4's example B1 uses `G4Cons` and `G4Trd`, so I guess we should add these next.

We should find a way of reusing the `phi_*` and `theta_*` members. Mixins?

**Comment by jacg** [comment]
And the main readme should be rewritten to use the new interface.

**Comment by jacg** [comment]
In the end I went with macros over mixins. It's on my `solid-reuse` branch.

**Comment by jacg** [comment]
This is done, isn't it? Apart from rewriting the README. (I'll do that right now, if it can be done quickly.)

We'll probably want to add more concrete implementations, but that belongs in a separate issue.

**Comment by gonzaponte** [comment]
Yes.
