### ISSUE TITLE
Consider a run manager abstraction

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#31]
Something that catches problems like 

+ failure to specify one of the mandatory classes (although `n4::action` already helps there)
+ failure to set the physics list before the generator

preferably at compile time.

This would probably be yet another builder pattern.

The physics-list-before-generator could be overcome by keeping the physics list in the builder until after the generator has been set. Completely omitting something mandatory could be dealt with by

+ Easy: run-time error with nice message, when the build method is called.
+ Harder, but preferable: compile-time error if you try to build before specifying everything that's needed. Getting clear error messages will be tougher than with the run-time version, so maybe the run-time version isn't so bad after all.

**Comment by jacg** [comment]
Note that (an *extremely* basic) `np::run_manager` was added in 9dac7ea.

<hr/>

As discussed in #34, we should be able to reduce the noise of something like this

``` c++
auto run_manager = n4::run_manager();
run_manager -> SetUserInitialization(new FTFP_BERT{0});
run_manager -> SetUserInitialization(n4::geometry(my_geometry));
run_manager -> SetUserInitialization(n4::actions(n4::generator([](auto){})));
run_manager -> Initialize();
```
to something more like this
```c++
auto run_manager = n4::run_manager()
  -> physics<FTPF_BERT>(0)
  -> geometry(my_geometry)
  -> actions(my_generator)
  -> init();
```
But we have to be careful not to lose flexibility and generality. For example, the old interface allows this
```c++
auto physics_list = new FTFP_BERT{verbosity};
physics_list -> ReplacePhysics(new G4EmStandardPhysics_option4{});
physics_list -> RegisterPhysics(new G4OpticalPhysics{});
run_manager  -> SetUserInitialization(physics_list);
```
and this
```c++
auto run_manager = n4::run_manager();
run_manager -> SetUserInitialization((new n4::actions{two_gammas_at_origin})
    -> set((new n4::stacking_action) -> classify(kill_secondaries))
    -> set (new n4::stepping_action{count_unscathed}))
    ...
```
The latter, along similar lines to what is being suggested at the `n4::run_manager` level, could be abbreviated to something like 
```c++
auto run_manager = n4::run_manager()
    -> actions(two_gammas_at_origin)
      -> stacking() -> classify(kill_secondaries)
      -> stepping(count_unscathed)
   ...
```
though the implicit bracketing may be more trouble than it is worth There are numerous alternatives to explore in this space.

**Comment by jacg** [comment]
Summary of what has been done:

+ Added `.physics()`, `.geometry()` and `.actions()` as neater alternatives to `SetUserInitialization`.
+ More work needs to be done on `.actions()` to deal with their internal structure *conveniently*
+ Need to address use cases which need `GetRunManager()`. We probably want a single spelling which both creates a new run manager, and finds an already existing one.
+ Probably need to change value semantics to pointer semantics, to make scoping more flexible. See https://github.com/jacg/nain4/blob/05cfb03fa105096b8398a70162dc297c5db85d48/nain4/test/trivial-full-app-test.cc#L266-L277

**Comment by jacg** [comment]
A general typestate would be quite a pain to implement. But perhaps it's worthwhile to start off with two states for the run manager:

1. uninitialized
2. initialized

The `.init()` method of the former would return the latter. The latter would not have the `physics`/`actions`/`geometry`/`init` methods. The former would not have `beam_on` etc. We'd need to look into the other bazillion methods run manager offers, and until we've understood and classified them all, we'll still need a `here_be_dragons` method, which should probably be renamed to something like `ask_the_developers_to_implement_the_method`.

An immediate benefit would be that the move semantics we just added to the mandatory setters (`.physics()` etc.) would probably become superfluous. Hmm, they may already be superfluous: I'd have to think about this when I'm more awake.

**Comment by jacg** [comment]
Eliding details, it might look something like this
```c++
class run_manager {
public:
  run_manager& physics (PHYSICS * x) { manager_ -> SetUserInitialization(x); return *this; }
  run_manager& geometry(GEOMETRY* x) { manager_ -> SetUserInitialization(x); return *this; }
  run_manager& actions (ACTIONS * x) { manager_ -> SetUserInitialization(x); return *this; }
  unique_ptr<initialized_run_manager> init() { return make_unique<initialized_run_manager>(manager_.release()); }
private:
  unique_ptr<G4RunManager> manager_;
};

class initialized_run_manager {
public:
  void beam_on(unsigned n) { manager_ -> BeamOn(n); }
private:
  friend unique_ptr<initialized_run_manager> run_manager::init();
  unique_ptr<G4RunManager> manager_;
};
```

**Comment by jacg** [comment]
Add these two functions and rename the above classes as suggested by the return types
```c++
           run_manager_before_init make_run_manager();
unique_ptr<run_manager_after_init>  get_run_manager();
```

+ `run_manager_before_init` should have private constructors and `make_run_manager` should be a friend, and the only public way of constructing it. (Just like `make_run_manager::init` is the only public way of constructing `run_manager_after_init`)

+ Both `{make,get}_run_manager` should error if they are called in the wrong state.

**Comment by jacg** [comment]
Although slightly stricter than necessary, we could use a pretty easy to implement typestate to impose the order of method calls
``` c++
auto run_manager = n4::make_run_manager()
  .physics(...)
  .geometry(...)
  .actions(...)
  .init()
```
roughly like this
``` c++
           run_manager_physics  make_run_manager()
           run_manager_geometry run_manager_physics ::physics()
           run_manager_actions  run_manager_geometry::geometry()
           run_manager_init     run_manager_actions ::actions()
unique_ptr<run_manager>         run_manager_init    ::init()
```
All we're losing is the ability to for `.actions()` to commute with its predecessors. I struggle to imagine how that would be a problem, but maybe there is one?

**Comment by gonzaponte** [comment]
> Although slightly stricter than necessary, we could use a pretty easy to implement typestate to impose the order of method calls

Didn't we say that this didn't add much to the interface because the user could instantiate the generator before the physics and there is no way to prevent that?

**Comment by jacg** [comment]
1. It statically ensures they are called exactly once, which we are doing dynamically at the moment.

2. We can get closer to ensuring that the generator is instantiated after the physics, by having `action` accept `std::function<G4blahPrimaryGenerator* ()>` and nothing else.

Less convinced that 2 is a good idea, but I like 1.

**Comment by jacg** [comment]
I've written a prototype, which gives quite nice errors at compile time and in LSP, things like
```
no member named 'actions' in 'nain4::run_manager::set_geometry'
```
and LSP proposes exactly the single method that is supposed to be used at each step, which is really quite pleasant.

But I'm becoming more convinced by the need to have `.actions(...)` accept only

1. `std::function<G4VUserPrimaryGeneratorAction* ()>`
2. `std::function<G4VUserActionInitialization* ()>`

The point is that it needs to be given a function, and that function will create the primary generator when it is called, which is when `.actions(...)` is called. This doesn't *guarantee* that the generator will not be instantiated sooner, but it makes it very much less likely. And if that does happen, then the G4 runtime error is *very* clear.

**Comment by gonzaponte** [comment]
Sounds good. My implementation has some segfault related to freeing the singleton memory that I don't quite understand yet. Unfortunately, this week has been a bit more intense than I expected. I should be more available from tomorrow.

I find 
```
no member named 'actions' in 'nain4::run_manager::set_geometry'
```
neater than my
```
no member named `actions` in `nain4::run_manager_geometry`
```

And 
> LSP proposes exactly the single method that is supposed to be used at each step, which is really quite pleasant.

 is really nice.

As for 
> I'm becoming more convinced by the need to have .actions(...) accept only [functions]

It will undoubtedly fit the nain4 philosophy (of promoting errors to compile time) much better, at the expense of forcing the user to write something slightly more elaborate. We can also accept `std::function<void (G4Event*)>`, right?

**Comment by jacg** [comment]
Done in 5242042.

**Comment by jacg** [comment]
One thing we forgot to do before merging: `run_manager::get()` should return a reference rather than a pointer. I'll do that quickly.

**Comment by gonzaponte** [comment]
I've been working on that today

**Comment by jacg** [comment]
I had to add/remove/replace 3 characters in the whole project, to achieve this. What am I missing?

**Comment by gonzaponte** [comment]
Ah, right, I thought it was more than that. I added a couple of tests for the get method.
Besides that I implemented and tested a couple of the run_manager methods and implemented one of the `.actions` methods left behind:

**Comment by jacg** [comment]
OK, if your stuff includes
```diff
-  static run_manager* get() {
+  static run_manager& get() {
```
and its consequences, then I won't push mine.

**Comment by gonzaponte** [comment]
It does, but you can push it anyway and I'll rebase. Please check the [test commit](https://github.com/jacg/nain4/commit/2fc2e05897da7c883a8ead04e62b5c36227d68ff) in my branch `more-rm` and let me know what you think.

**Comment by jacg** [comment]
> Please check the [test commit](https://github.com/jacg/nain4/commit/2fc2e05897da7c883a8ead04e62b5c36227d68ff)

Perhaps overkill? I don't think we need more than one test for this, because you end up checking that C++ bare pointers and references aren't completely broken.

But we do need to delete the copy constructor. It should be deleted implicitly because of the `unique_ptr`, but maybe it's worthwhile to do it explicitly.

**Comment by gonzaponte** [comment]
> It should be deleted implicitly because of the unique_ptr

It is. If you remove the `&` from `auto&` it doesn't compile because it attempts to use the copy constructor which is implicitly deleted.

**Comment by gonzaponte** [comment]
Hmm, but deleting it seems to break `default_run_manager`. Why is the copy constructor called on return?

**Comment by jacg** [comment]
Any reason why [this](https://github.com/gonzaponte/nain4/blob/eb2967aafd7d16c7c7b4c3006cfd65db56107f59/nain4/test/test-run-manager.cc#L126-L140) can't be implemented with `n4::actions`?

Just close over `count`.

**Comment by gonzaponte** [comment]
I tried. Maybe I did it wrong, but it goes down to `.actions(G4VUser*)` being private now. The other methods don't allow you to create an `actions` and use `-> set` on them, right?

**Comment by jacg** [comment]
> Why is the copy constructor called on return?

Because it needs to be copied out of the local scope to the caller. It needs to be moved. We want it to be unique, so this makes sense.

But then it's not clear to me why the lack of `&` on `auto` was failing before you deleted the copy constructor.

[I'm about to be unavailable until 16:00ish CEST.]

**Comment by jacg** [comment]
> I would assume that it would be moved, not copied.

No way! It's an lvalue (it has a name!) and you haven't used `std::move` on it.

> Might be due to [copy elision](https://en.cppreference.com/w/cpp/language/copy_elision)?

Copy elision, broadly speaking, only applies if you are naively invoking two constructors (one that makes a *new* thing, and one that *immediately* copies or moves the thing to its destination) . It avoids the copy/move, by constructing the new thing in its final destination, in the first place. In `default_run_manager` the initial construction of `run_manager` is a few layers/steps removed from the copy that might be elided, so this seems rather unlikely.
