### ISSUE TITLE
Rename `find_particle` to `particle`?

### ISSUE THREAD

**Issue by gonzaponte** [jacg/nain4#32]
When comparing these lines
```
IA material      NAME     { return G4NistManager        ::   Instance()->FindOrBuildMaterial(name         ); }
IA element       NAME     { return G4NistManager        ::   Instance()->FindOrBuildElement (name         ); }
IA find_logical  NAME_VRB { return G4LogicalVolumeStore ::GetInstance()->GetVolume          (name, verbose); }
IA find_physical NAME_VRB { return G4PhysicalVolumeStore::GetInstance()->GetVolume          (name, verbose); }
IA find_solid    NAME_VRB { return G4SolidStore         ::GetInstance()->GetSolid           (name, verbose); }
IA find_particle NAME     { return G4ParticleTable:: GetParticleTable()->FindParticle       (name         ); }
```

the last one looks a bit more like the first two than the other three.

**Comment by jacg** [comment]
Maybe all the `find_` prefixes should be removed.

I suspect I put them in front of  `material`, `element` and `solid` because we frequently *make* those ourselves, and I didn't want confusion between things that make them, and things that look for existing ones. We can also make materials, but elements and particles seem rather less likely.

The names of the functions that make new things are all sufficiently different from these that find them, so confusion seems unlikely. So I'd probably be happy to rename *all* the `find_`s.

**Comment by gonzaponte** [comment]
Even though one can create materials, they, together with elements and particles feel more static than the geometry-related ones (even though they are not actually static). Moreover, I think calling `n4::logical` (or solid or physical) can be misinterpreted, while `n4::material` cannot(*). I would personally keep the distinction.

(*) As I was writing this, I realized that `material` can also be confused since we have the `material_from_elements`. I'm a bit unsure now. I'm afraid I might be biased because I already know how to use some of the functionality and my pov is not super objective.

BTW, 

> We can also make materials

Should `n4::material` search for user-defined materials? It looks like a useful functionality.

**Comment by jacg** [comment]
> Even though one can create materials, they, together with elements and particles feel more static than the geometry-related ones (even though they are not actually static). 

We'd need to discover new physics, before we find the need to create an element or particle that isn't already present in G4. The need to create new materials is pretty common. Far less common than creating geometry components, but still *infinitely* more common that elements and particles.

But perhaps the geometry/non-geometry distinction is important.

> I think calling `n4::logical` (or solid or physical) can be misinterpreted, while `n4::material` cannot(*). I would personally keep the distinction.
> 
> (*) As I was writing this, I realized that `material` can also be confused since we have the `material_from_elements`.

Sorry, I was being lazy in my earlier reply. I meant that 2 is not significantly clearer than 1: 

1. `material`, `material_from_elements`
2. `find_material`, `material_from_elements`

BUT from the perspective of someone who just sees `material` written down, and is unaware of other related n4 names, especially if familiar with the more commonly used geometry-related names ... it's not obvious ... and it seems that you are illustrating exactly this point: 

> I'm a bit unsure now. I'm afraid I might be biased because I already know how to use some of the functionality and my pov is not super objective.

I don't know. I need to take time to think about this calmly.

> Should `n4::material` search for user-defined materials? It looks like a useful functionality.

I think it already does, does it not? Yes, it does: https://github.com/jacg/nain4/blob/6d17884aeecd40e76ad9c249eee81e1a83f1a29d/nain4/test/test-nain4.cc#L58-L74

**Comment by gonzaponte** [comment]
Aha! I didn't know that happened automatically.

**Comment by jacg** [comment]
Seems more trouble than it is worth, and there is no obvious way to improve matters significantly.
