### ISSUE TITLE
nain4 distribution

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#33]
Here are some observations related to distribution and installation of `nain4`. They will probably give rise to some smaller, more targeted issues or PRs.

# `nain4` and `Geant4`

n4 is an improved API for G4, as such an installation of G4 is required to use n4. n4 is developed against a specific version of G4, and it might not work with others. To what extent should n4 impose a G4 version on the user? In principle, we should give users the freedom to use any reasonably recent version of G4 with n4. This would require testing n4 against those different versions, and maintaining code that caters for differences in supported G4 versions.

This greatly increases the burden on the development team, so we probably can't afford to do this. So we probably have to say that we only support one G4 version in n4 ... unless and until the project really takes off and gets more manpower[^1].

[^1]: It *should* go without saying that *man* in *manpower* refers to *any* member of the hu*man* species. Though any dolphins, sea otters, chimpanzees, or members of *any* other species who might be interested and able to contribute, would be most welcome to do so. This is an inclusive project: if you are interested and *able* to contribute, you're *very* welcome! Interest and ability are *all* that matters.

# `nain4` and `Catch2`

n4 has Catch2 as a development dependency. As such, it would be reasonable for n4 users, as opposed to n4 developers, not to need Catch2 to be installed.

OTOH, half of the point of n4 is to promote automated testing of G4 apps, with the aim of making it standard practice: **everybody** should be writing tests for their G4 apps, **as a matter of course**. From this perspective, it seems reasonable to make Catch2 a dependency for all n4 users.

OTOOH, G4 app authors can still benefit immensely from n4, even if they don't write a single test. From this perspective, Catch2 should be optional.

# Nix

While people should have the freedom to faff around and (try to) install whatever versions of n4, G4, Catch2 and other dependencies and tools they like, using whatever means they like, and we should try to make this as easy for them as possible ... in general, this is an absolute nightmare, and our resources are limited.

I am convinced that Nix, and specifically Nix flakes, is the best long-term solution to distributing n4 and providing n4 development environments.

Yes, a general Nix solution is a pain to set up (and having to cater for MacOS more than doubles the work, and I'm not sure about WSL[^2]), but once you have it, it is a robust solution that absolves *every* user from the need to deal with dependency hell.

[^2]: `GaP` has given us one data point suggesting that (if we remember to use `nixGL` for the GUI) everything works. It also gave us a graphical demonstration of the dependency hell you get into, if users have to install their own junk.

However, the current flake that comes with `nain4` conflates provision of 3 different things:

1. `nain4` itself
2. a development and testing environment for the development of `nain4`
3. a development and testing environment for the development of G4 applications that use `nain4`

**Comment by gonzaponte** [comment]
The aspects of `Geant4` that `nain4` deals with are fairly stable. I think it's reasonable to assume that `nain4` can support a given major version, but I can be proven wrong very quickly. Nonetheless, this would require extending testing to every possible minor version, which would also be a pain.

**Comment by jacg** [comment]
I'm not thinking of minor versions. I'm just slightly wary of situations such as when Nexus holding off migrating to a new major G4 version for quite some time, because the physics was different or not yet validated, while in `nain4` I was relying on interfaces which were only present in the new version. 

But I agree

+ This is not going to be a frequent problem, and probably not extremely serious, even then.
+ It would be a huge pain to test, even without the minor versions.

**Comment by jacg** [comment]
I think it's pretty clear that we will be distributing `nain4` with a Nix flake, and providing flake templates for bootstrapping projects, and the flake of the latter will provide outputs for distributing/deploying the client's app including via containerization with Docker and Singularity (#66).

Unless we find that Nix doesn't allow us to do something fundamentally necessary, I think that our attitude must be that we do not have the resources to support efforts to use nain4 without Nix.
