### ISSUE TITLE
Provide a user-friendly set of headers for accessing `nain4` components.

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#36]
At the moment `nain4` is implemented in only 4 files: `{nain4,g4-mandatory}.{hh,cc}`.

This is very convenient for the user, and worked quite well while `nain4` was in its infancy. As we are adding more features to `nain4` this is going to become more troublesome.

We need to split the implementation up into more fine-grained files, without going overboard. I certainly wouldn't want to oblige the user to include dozens of headers, but we would have to examine the compile-time cost of keeping coarse-grained headers.

Perhaps we could have a small number of coarse-grained headers that include a number of very fine-grained ones. The former for convenience in client code, especially in didactic examples, and the latter for use if and when compile times suffer in real-world projects.

**Comment by gonzaponte** [comment]
I've had this in mind for a while and I think this

> Perhaps we could have a small number of coarse-grained headers that include a number of very fine-grained ones

could be a good solution. To start with one can use the coarse-grained headers and refactor the code later to use finer-grained ones.

**Comment by jacg** [comment]
We need to stabilize the headers that clients are expected to include, *before* we get more client projects depending on the old set of headers.

**Comment by jacg** [comment]
We should probably have headers related to tasks that the user is going to carry out it a single file. For example, the file containing the user's `main` is almost certainly going to have

+ run manager
+ ui
+ g4-mandatory

so these should probably be available via a single header, maybe called `n4-main.hh`. But `n4-main.hh` could simply be

```c++
#include <n4-run-manager.hh>
#include <n4-ui.hh>
#include <n4-user-mandatory.hh>
```



Similarly, stuff that will almost certainly be used in constructing geometries should probably be available in an `n4-geometry.hh`.
