### ISSUE TITLE
Allow `_delta` and `_end` angle combination

### ISSUE THREAD

**Issue by gonzaponte** [jacg/nain4#49]
Right now we can set angles like (taking phi as an example from a test):

```c++
auto tubsrz = [&] (auto name) { return n4::tubs(name).r(1).z(1); };
auto phi_s  = tubsrz("phi_s" ).phi_start(start) /*.end(360)*/   .solid();                        
auto phi_se = tubsrz("phi_se").phi_start(start).phi_end  (end  ).solid();                        
auto phi_sd = tubsrz("phi_sd").phi_start(start).phi_delta(delta).solid();                        
auto phi_es = tubsrz("phi_es").phi_end  (end  ).phi_start(start).solid();                        
auto phi_ds = tubsrz("phi_ds").phi_delta(delta).phi_start(start).solid();                        
auto phi_e  = tubsrz("phi_e" ).phi_end  (end  ) /* .start(0) */ .solid();                        
auto phi_d  = tubsrz("phi_d" ).phi_delta(delta) /* .start(0) */ .solid();   
```

There is one combination missing that doesn't work:
```c++
auto phi_de = tubsrz("phi_de").phi_delta(delta).phi_end   (end) .solid(); 
```

**Comment by jacg** [comment]
If we implement this, we will have to (as it stands) test it in all the shapes that use angles, for each angle in that shape. This is leading to an explosion of boring tests, repeated many times across many shapes. This is kinda pointless, as all the angle implementations share the same underlying implementation. The same applies to the linear coordinates.

Perhaps we should do absolutely minimal testing for each coordinate's setters, in the `n4::shape`s (essentially, that the coordinate is present at all, in that shape), and thoroughly test the underlying implementation for each coordinate, in its own separate test.
