### ISSUE TITLE
G4SubtractionSolid

### ISSUE THREAD

**Issue by Hiitsaso** [jacg/nain4#5]
Hi!

Is there a way to perform a subtraction between two solids with nain4? Or is it necessary to do it with Geant4 and then define a G4LogicalVolume and do G4PVPlacement?

Thanks!

**Comment by jacg** [comment]
There are no `nain4` abstractions for the boolean solids, at the moment.

For now, you have to use G4 constructors to create the boolean solid and its logical volume. Once you have that, you can `n4::place(...)` it; no need to resort to `G4PVPlacement`.

`n4::volume` is useful in the very common case where you need to create a logical volume and a primitive solid that go together. It allows you to express the two constructions in a single expression, without repeating identical information such as the name.

In the case of boolean solids, it's not *immediately* obvious what abstraction would significantly improve on what G4 provides. But it would certainly be worth considering. If you have any ideas about an interface that would make your life easier in these cases, do let me know!
