### ISSUE TITLE
Warnings about shadowing when compiling with gcc

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#6]
When compiling `nain4` client code with gcc, it spews screenfuls of warnings about shadowing, drowning out any interesting warnings that might be emitted.

This needs to be silenced, without requiring the client to do anything. So, probably remove the shadowing from the `nain4` code, though I suspect it's perfectly kosher C++.

Or we could consider [gcc diagnostic pragmas](http://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html), but removing the shadowing is going to be a more general, more robust and less noisy approach.

**Comment by gonzaponte** [comment]
Another warning to take care of, albeit of a different nature:
```
nain4.hh:66:16: warning: narrowing conversion of ‘std::forward<int>((* & args#0))’ from ‘int’ to ‘G4double’ {aka ‘double’} [-Wnarrowing]
   66 |   auto solid = new SOLID{std::forward<NAME>(name), std::forward<ArgTypes>(args)...};
```

**Comment by gonzaponte** [comment]
Yes, it's not nain4's fault. However, it is slightly annoying to type the decimal point to avoid this warning. I was wondering if there is anything that can be done from this side.

**Comment by jacg** [comment]
Yes, it's annoying. Just be glad it's not Rust, where it would be a hard error ;-)

I doubt that there's anything that can be done here, as it simply forwards whatever the client passes in, without any interference, to whatever underlying G4 constructor receives the information. It's a very general pattern, which allows a single implementation to cater for all the G4 solids, even ones which haven't been invented yet. That generality means that we can deal with any specifics like narrowing of integers to floats.

**Comment by gonzaponte** [comment]
I'm working on this. Do we want to use the pragma directive for the whole file or every time there is a constructor that shadows a variable? The latter would introduce a lot of noise in the code, but it would be technically safer.

**Comment by jacg** [comment]
I think that the cost of the extra noise outweighs the benefits of doing it properly. So let's just do it once per file.

Joe End User probably needs these warnings in user code, but we can reasonably expect a `nain4` *contributor* to be equipped to figure it out without the hint, if a shadowing problem arises in `n4` source code.
