### ISSUE TITLE
Support user-defined CLI in n4::ui

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#61]
Some variation on this theme

```c++
auto n4::argspec = ...
auto args = n4::parse_args(argc, argv, argspec);

auto run_manager = n4::run_manager::create()
    .physics(...)
    .geometry(args.geometry)
    .actions(...)
    
n4::ui{args};
```

Of course, all of this, and more, can be achieved with G4 macros, but being able
to pass info via the CLI could be very convenient.

**Comment by jacg** [comment]
User 1 needs to submit jobs to a queue, which implies injecting some information that distinguishes the jobs so that different random seeds can be set, and output files can be distinguished.

This might be done by 

+ Setting this information in G4 macro files
+ Inspecting the environment, looking for SLURM job ids
+ Relying on SLURM job directories (won't work for the random seed)
+ Passing the job id in on the CLI.

The last one is probably the most convenient, and completely unsupported by `n4::ui`.

**Comment by gonzaponte** [comment]
And the first one ensures reproducibility (without having to change the job file) , which might or might not be important for User1 at the moment.

**Comment by jacg** [comment]
... but it does require changing the macro file. Not sure how you'd do that without changing the job file too.

**Comment by jacg** [comment]
In the short term we could add an extra optional integer argument to `n4::ui` for this specific use case (which is going to be very common). That is, pass in another integer and it becomes available to the user inside the program, to do with as he pleases.

**Comment by gonzaponte** [comment]
I was thinking that User1 was doing the same as I would do for this sort of thing, which is probably an overkill for his case. Nevermind.

> In the short term we could add an extra optional integer argument to n4::ui for this specific use case
Yup, agreed.

**Comment by jacg** [comment]
Now that #142 is complete, the user can specify any Geant4 UI command on the CLI (without having to modify any macro files) which should cater for pretty much any use case, as the user can write a messenger for just about anything and use that messenger via individual CLI arguments.
