### ISSUE TITLE
run_manager .actions() compile-time error

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#63]
Something needs to change WRT `run_manager::actions`

I was the one who wanted to make it a compile-time error to pass an already constructed action, and yet I myself don't understand the error when it appears out of context, so what chance does a poor C++/G4 newbie have!

Given that G4's run-time error is unusually clear in this case, and that we can't completely prevent the wrong thing from being done at compile time anyway, I suggest that we simply allow the action to be passed in directly.

**Comment by gonzaponte** [comment]
I agree. Probably worth removing the pointer restriction immediately. We should not forget that we still have to address the last stage of #30.
