### ISSUE TITLE
Provide default nain4 app and/or template

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#7]
EDIT: this (see task list, below) needs to be split into separate, smaller issues, which can be knocked off in reasonable amounts of time.

Provide a default app which allows a new user to write a fully-working Geant4 application in only a few lines of code.

It should be possible to use this as a starting point for writing your own applications, by gradually replacing the defaults with your own logic.

Ideally, it would also come with automated tests (and a GitHub Action), in order to encourage the user to write and run tests from the very beginning.

EDIT: we are making a nix flake template for bootstrapping client nain4 projects
TASK LIST
+ [ ] Add instructions to README
+ [ ] Add documentation to the mdbook
+ [ ] Add tests for the template
+ [ ] Add GHA steps which catch template-breaking nain4 changes
+ [ ] Add exhaustive CHANGEMEs
+ [ ] Add more functionalities to the app
+ [ ] Configure binary cache with `nixConfig` in the template's flake. (This whole topic appears to be almost completely undocumented in Nix, but here's an example in the wild: https://github.com/divnix/digga/blob/main/examples/devos/flake.nix#L4-L14)

**Comment by gonzaponte** [comment]
I understand that we want two things:
1. a working example
2. a template to be filled (without replacements)

is this correct?

As for 1. IIUC we want a main that can discover the geometry, actions, etc. defined by the user and run them. In that way, the user would only need to compile their code linking it to the app?

And for 2. we want a simple main that uses empty instances (geometry, actions, etc) in the same file that the user needs to fill, right?

**Comment by gonzaponte** [comment]
Ok, I think I understand.

**Comment by jacg** [comment]
Also, for the documentation to be digestible, the code in the tutorials and examples **cannot** be spread out over 13 files, and really shouldn't waste space on defining class boilerplate in the same file, à la [trivial-full-app-test.cc](https://github.com/jacg/nain4/blob/master/nain4/test/trivial-full-app-test.cc). In fact, we want something like that, but without the classes.

We need to find an app that strikes a good balance between being not too trivial on the one hand, and not too long on the other.

And we probably need to do #8 first. Ideally the user clones the repo, types `just start` and gets a pretty Qt UI showing a geometry ... and can proceed from there.

**Comment by gonzaponte** [comment]
> In fact, we want something like that, but without the classes.

Seeing that test got me walking in the wrong direction, but I'm on a good track now.

**Comment by jacg** [comment]
Yeah, the purpose of that test is primarily to document what is needed to get going in *standard* G4. In a way, the purpose of that test is to demonstrate that the descriptive comments near the top of the file aren't complete bollocks.

**Comment by jacg** [comment]
I'm in two minds as to whether include a sensitive detector or not.

Without a sensitive detector it's kinda pointless, but it will compile, run, give you a pretty picture, and you can even shoot some particles and see their tracks being drawn.

Adding a sensitive detector and doing something with the results, could then be decent early didactic examples.

**Comment by gonzaponte** [comment]
I'm almost done with the most basic example. I think we can build on that and provide a second one that adds a sensitive detector, right?

**Comment by jacg** [comment]
Sounds good.

**Comment by gonzaponte** [comment]
As a matter of fact, we can turn this issue into a checklist of the first set of examples we want to provide, what do you think=

**Comment by jacg** [comment]
Yes, though if it starts getting too long, we might want to break it up into separate issues. But we can certainly start that way.

**Comment by jacg** [comment]
A few things to remember to fix in #29:

+ Talk about `CMakeLists.txt`
+ Give explicit instructions on how to run the example (directly call executable, justfile)
+ State what the expected outcome is

Not sure what the best way would be to maintain such a task list. If left here, it will be overlooked. Up in the initial description?

**Comment by gonzaponte** [comment]
Since we are heavily involved in this, I doubt that this particular task (I mean *just* creating the most basic app) will be overlooked. But maybe moving forward we can have an issue (or a project) to track the progress and sub-issues to discuss each task?

**Comment by jacg** [comment]
A project, I guess. It's been a while since I touched one, so I forget exactly how they work, and they have probably evolved since then. You?

**Comment by gonzaponte** [comment]
I've only used classical projects. It seems like there is a new version that works differently that I haven't even looked at it yet, but seems to be the only option in this repo. Also, it looks like you are the only one that can create one here.

**Comment by jacg** [comment]
You should have received a collaboration invite by now. Today. ... Which I see you have accepted. Do I need to set some extra permissions for you somewhere?

**Comment by gonzaponte** [comment]
If I try to link a new project from the projects tab, it asks me to go to "my" profile to create one, but it takes me to yours. I guess it can only be done by the owner?

**Comment by jacg** [comment]
There must be a way of giving you sufficient rights. I think I can make you admin, or something like that, but I can't find where.

**Comment by jacg** [comment]
Hmm, maybe not on personal repos. So we have to make an organisation? I have a huge stack of other things to get through today, so I really don't want to open this can of worms right now.

**Comment by gonzaponte** [comment]
Looks like the projects are no longer associated with repositories, but with users. After opening a project in your profile you can link it from the repository. I opened a project in my profile to test it, but I cannot link it from the repo, so I guess you would have to do it yourself.

**Comment by jacg** [comment]
This has been split into finer-grained issues:

+ #104
+ #105 
+ #106 
+ #107
