### ISSUE TITLE
`n4::box::xyz` confusing WRT `xy` etc.

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#71]
We have

``` c++
.x   (  l  )
.xy  (  l  )
.xyz (x,y,z)
.cube(  l  )
```
The confusion comes from that fact that in the two-letter cases, you must supply one value which is assigned to all the named letters, while in `.xyz` each named letter must be given a separate value.

The `.xyz` method is very useful, and it's name is great ... in the absence of the other methods. With the other methods, it breaks symmetry.

**Comment by jacg** [comment]
We've decided to keep it as is?

**Comment by gonzaponte** [comment]
It is documented and the non-existence of `xy(G4double, G4double)` and `xyz(G4double)` probably makes it safe enough, so I'm happy to keep it as is.
