### ISSUE TITLE
Fix test-fetch-content-recompile in macOS

### ISSUE THREAD

**Issue by gonzaponte** [jacg/nain4#88]
This test ensures that when a project includes `nain4` via `FetchContent`, it can recompile without the need for an internet connection. This test works fine in ubuntu, but the command used in the test to prevent network connections (`iptables`) does not exist in macOS (or maybe it does, but it would need to be installed). With #82 we finally got macOS working in GHA. During the process, we realized that the test was passing on macOS when it shouldn't. The reasons for this are:
1. The command `iptables` failed, but the bash script continued running
2. Because `iptables` failed, no network restrictions were applied, which would have made the test fail

For 1. we attempted a5f796fb432201dbe010822d92e83a8ccd8e9055, but it didn't seem to have an effect (which should also need to be investigated). For 2. a first attempt based on `pfctl` was unsuccessful as GHA was getting stuck on that command (I believe).

**Comment by jacg** [comment]
I've disabled this test in 4d4aa78, for now.

**Comment by jacg** [comment]
This is irrelevant now that we have migrated from cmake to meson.
