### ISSUE TITLE
Problems running n4 examples

### ISSUE THREAD

**Issue by mdcge** [jacg/nain4#97]
After the successful installation of nain4, we proceeded to try to run the examples, first using the recommended ```just g4-examples/run B1```. This gives the error:
```
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
```
as well as (further down, in the backtrace):
```
[PID=28803, TID=-2][30/37]> /nix/store/2nm3pfqc21fa0qpha7nl3cs3597d0ghx-geant4-11.0.4/lib/libG4intercoms.so(_ZN20G4UIcontrolMessenger11SetNewValueEP11G4UIcommand8G4String+0x32d) [0x7ffff31cd2cd]
```
(there are many lines like these, but all start with ```/nix/store```).

Then, when attempting to run ```just test-examples```, we got the error:
```
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "FindNain4.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Nain4", but
  CMake did not find one.

  Could not find a package configuration file provided by "Nain4" with any of
  the following names:

    Nain4Config.cmake
    nain4-config.cmake

  Add the installation prefix of "Nain4" to CMAKE_PREFIX_PATH or set
  "Nain4_DIR" to a directory containing one of the above files.  If "Nain4"
  provides a separate development package or SDK, be sure it has been
  installed.
```
This problem was found on @mariandbt 's machine.

**Comment by jacg** [comment]
> ```
> qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
> ```

See #60.

**Comment by jacg** [comment]
Closing this as it is probably covered by a combination of 

+ #60
+ The new flake template which has recently landed on master, and is about to be documented more extensively: #102.
