### ISSUE TITLE
Status of `mdbook-admonish`

### ISSUE THREAD

**Issue by gonzaponte** [jacg/nain4#98]
We want to use it, but it breaks our style. We [opened an issue](https://github.com/tommilligan/mdbook-admonish/issues/117) in their repo and they suggest updating to a newer version. However, the nix package is not up to date. We need to either wait for the updated version or submit a PR to update it.

**Comment by gonzaponte** [comment]
Opened without description. Added now.

**Comment by jacg** [comment]
I have a branch somewhere, where I'm trying to override the version. Can't remember what the problem was, and haven't had time to look at it recently.

**Comment by jacg** [comment]
`nixos-unstable` has 1.10.2. The change looks trivial: only the version and two hashes change... aaaand now I remember what the problem was: there was something very weird going on when I tried to change the `cargoHash`.

**Comment by jacg** [comment]
I seem to have found a way of hacking around this: see the `admonish-version` branch.

As it pulls in clang 15 and rust 1.69 and uses them to compile admonish, we should probably avoid propagating it to client flakes (unless we can cache the result reliably). We currently propagate `mdbook` to the clients, which we should probably not do.

**Comment by jacg** [comment]
Nixos 23.11 looks like it will contain `mdbook-admonish` 1.13.0, so let's just wait until it is released. Then we can upgrade our flake to 23.11 and get the binary-cached `mdbook-admonish` with the fix, for free.
